### ISSUE TITLE
代码什么时候能整理好呢？坐等学习

### ISSUE THREAD

**Issue by joe0327** [zhijing-jin/TitleStylist#1]

**Comment by zhijing-jin** [comment]
Hi,

Thanks for asking! We are preparing it. Optimally, it can come out in 7 days!

:)

Best,
Zhijing

**Comment by zhijing-jin** [comment]
Thank you for the patience. We are a bit busy refining the camera-ready version of our paper right now. We will try our best to release the code ASAP.

**Comment by zhijing-jin** [comment]
Hi Joe, good news! We have just finished tidying up our code. It is now merged into my co0-author's github at https://github.com/jind11/TitleStylist.

Hope it helps :)!

**Comment by joe0327** [comment]
Great！ @zhijing-jin
